# -*- coding: utf-8 -*-
"""lora-finetune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Db8HL098rW8cX4ujp5qx3bBDWQOwGrzW
"""

import torch
print(torch.cuda.is_available())

import sys
import subprocess
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "transformers", "datasets", "peft", "accelerate", "bitsandbytes"])

from google.colab import files
files.upload()

from datasets import load_dataset

dataset = load_dataset("json", data_files="dataset.jsonl")

print(dataset)

from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "microsoft/phi-3-mini-4k-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype="float16"
)

from huggingface_hub import login

login("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")